/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sohak9660
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SubTittle = new javax.swing.JLabel();
        Diameter = new javax.swing.JTextField();
        Topping4 = new javax.swing.JCheckBox();
        SecondSubTittle = new javax.swing.JLabel();
        Topping3 = new javax.swing.JCheckBox();
        Topping2 = new javax.swing.JCheckBox();
        Topping1 = new javax.swing.JCheckBox();
        OutputLabel = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel1.setText("Pizza Price Calculator");

        SubTittle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubTittle.setText("Enter The Diameter of the Pizza in Inches");

        Diameter.setText("Enter");
        Diameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiameterActionPerformed(evt);
            }
        });

        Topping4.setBackground(new java.awt.Color(102, 102, 255));
        Topping4.setText("Vegtables");
        Topping4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping4ActionPerformed(evt);
            }
        });

        SecondSubTittle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SecondSubTittle.setText("Choose any of the following toppings");

        Topping3.setBackground(new java.awt.Color(102, 102, 255));
        Topping3.setText("Chicken");
        Topping3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping3ActionPerformed(evt);
            }
        });

        Topping2.setBackground(new java.awt.Color(102, 102, 255));
        Topping2.setText("Pinaple");
        Topping2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping2ActionPerformed(evt);
            }
        });

        Topping1.setBackground(new java.awt.Color(102, 102, 255));
        Topping1.setText("Pepporoni");
        Topping1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping1ActionPerformed(evt);
            }
        });

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SecondSubTittle)
                                    .addComponent(SubTittle)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Topping1)
                        .addGap(33, 33, 33)
                        .addComponent(Topping2)
                        .addGap(55, 55, 55)
                        .addComponent(Topping3)
                        .addGap(29, 29, 29)
                        .addComponent(Topping4)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Calculate)
                        .addGap(18, 18, 18)
                        .addComponent(Diameter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(OutputLabel)
                        .addGap(224, 224, 224))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubTittle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SecondSubTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Topping4)
                    .addComponent(Topping3)
                    .addComponent(Topping2)
                    .addComponent(Topping1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(OutputLabel)
                .addGap(63, 63, 63))
        );

        FileMenu.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem1);

        jMenuBar1.add(FileMenu);

        HelpMenu.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        HelpMenu.add(jMenuItem2);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiameterActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_DiameterActionPerformed

    private void Topping1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping1ActionPerformed
        // TODO add your handling code here:
         double price, labour, cost, rent, material, pepporoni, prinaple, chicken, vegtables;
        String Check = "";
        //The Entering Part
         cost = Double.parseDouble(Diameter.getText());
         
         labour = 1;
         rent = 1.5;
         material = 0.5 * cost;
         price = labour + rent + material;
         pepporoni = price + 1.5;
         
        Check = Topping1.getText();
         OutputLabel.setText("The Price of the Pizza is " + pepporoni + "0$");
    
    }//GEN-LAST:event_Topping1ActionPerformed

    private void Topping2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping2ActionPerformed
        // TODO add your handling code here:
        //Repeating So the Samething happens in Box 2
        double price, labour, cost, rent, material, pepporoni, prinaple, chicken, vegtables;
        String Check = "";
        //The Entering Part
         cost = Double.parseDouble(Diameter.getText());
         
         labour = 1;
         rent = 1.5;
         material = 0.5 * cost;
         price = labour + rent + material;
         pepporoni = price + 1.5;
         
        Check = Topping1.getText();
         OutputLabel.setText("The Price of the Pizza is " + pepporoni + "0$");
    }//GEN-LAST:event_Topping2ActionPerformed

    private void Topping3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping3ActionPerformed
        // TODO add your handling code here:
          double price, labour, cost, rent, material, pepporoni, prinaple, chicken, vegtables;
        String Check = "";
        //The Entering Part
         cost = Double.parseDouble(Diameter.getText());
         
         labour = 1;
         rent = 1.5;
         material = 0.5 * cost;
         price = labour + rent + material;
         pepporoni = price + 1.5;
         
        Check = Topping1.getText();
         OutputLabel.setText("The Price of the Pizza is " + pepporoni + "0$");
    }//GEN-LAST:event_Topping3ActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:\ double labour, storeCost, Materials, cost;
        double price, labour, cost, rent, material, pepporoni, prinaple, chicken, vegtables;
        String Check = "";
        //The Entering Part
        cost = Double.parseDouble(Diameter.getText());

        labour = 1;
        rent = 1.5;
        material = 0.5 * cost;
        price = labour + rent + material;
        pepporoni = price + 1.5;

        OutputLabel.setText("The Price of the Pizza is $" + price + "0");

    }//GEN-LAST:event_CalculateActionPerformed

    private void Topping4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping4ActionPerformed
  double price, labour, cost, rent, material, pepporoni, prinaple, chicken, vegtables;
        String Check = "";
        //The Entering Part
         cost = Double.parseDouble(Diameter.getText());
         
         labour = 1;
         rent = 1.5;
         material = 0.5 * cost;
         price = labour + rent + material;
         pepporoni = price + 1.5;
         
        Check = Topping1.getText();
         OutputLabel.setText("The Price of the Pizza is " + pepporoni + "0$");    }//GEN-LAST:event_Topping4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        OutputLabel.setText("Enter your Pizza's Diameter then click calculate then press 1 of the toppings");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.JTextField Diameter;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JLabel SecondSubTittle;
    private javax.swing.JLabel SubTittle;
    private javax.swing.JCheckBox Topping1;
    private javax.swing.JCheckBox Topping2;
    private javax.swing.JCheckBox Topping3;
    private javax.swing.JCheckBox Topping4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
